name: Deploy Wolplay

on:
  push:
    branches:
      - backend_staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /var/www/backend || exit

            # On configure SSH pour accepter GitHub sans poser de question
            mkdir -p ~/.ssh
            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

            # Initialisation Git via SSH
            if [ ! -d ".git" ]; then
              echo "🚀 Premier clonage via SSH..."
              git clone git@github.com:Neihos/wolplay.git .
            fi

            # Mise à jour
            git fetch origin backend_staging
            git reset --hard origin/backend_staging

            # Installation & Laravel (Chemins standards)
            composer install --no-dev --optimize-autoloader --no-interaction

            if [ ! -f ".env" ]; then
              cp .env.example .env
              php artisan key:generate
            fi

            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Permissions
            chmod -R 775 storage bootstrap/cache


            # git merge staging/backend_staging --allow-unrelated-histories
            # git push staging main:backend_staging --force
